- name: inice_muons
  feature_patterns:
    - mu%s_pos_x
    - mu%s_pos_y
    - mu%s_pos_z
    - mu%s_dir_x
    - mu%s_dir_y
    - mu%s_dir_z
    - mu%s_radius
    - mu%s_log_energy
  n_objects: 10
  embedding_dim: 16
  layers_list: [128, 128]
  hidden_activation: relu
  final_activation: sigmoid
  dropout: 0.1
  kernel_regularizer: 1e-4
  aggregation_method: sum
  pad_and_mask_empty_objects: false
  epsilon_std: 0

- name: elosses
  feature_patterns:
    - eloss%s_log_energy
    - eloss%s_pos_x
    - eloss%s_pos_y
    - eloss%s_pos_z
    - eloss%s_distance
  n_objects: 10
  embedding_dim: 16
  layers_list: [128, 128]
  hidden_activation: relu
  final_activation: sigmoid
  dropout: 0.1
  kernel_regularizer: 1e-4
  aggregation_method: sum
  pad_and_mask_empty_objects: false
  epsilon_std: 0

- name: shower_muons
  feature_patterns:
    - shower_mu%s_pos_x
    - shower_mu%s_pos_y
    - shower_mu%s_pos_z
    - shower_mu%s_dir_x
    - shower_mu%s_dir_y
    - shower_mu%s_dir_z
    - shower_mu%s_radius
    - shower_mu%s_log_energy
  n_objects: 10
  embedding_dim: 16
  layers_list: [48, 48, 48]
  hidden_activation: relu
  final_activation: sigmoid
  dropout: 0.1
  kernel_regularizer: 1e-4
  aggregation_method: sum
  pad_and_mask_empty_objects: false
  epsilon_std: 0

