- log_primary_pos_z
- log_rho
- log_primary_length
- log_energy
- interaction_height
- cos_zenith
- pdg_map
- log_energy_per_nucleon
- mu_bundle_depth
- log_mu_multiplicity
- mu_bundle_log_energy
- mu_bundle_energy_per_nucleon
- mu_bundle_singleness
- mu_bundle_leading_energy_fraction
- n_eloss
- eloss_total
- log_shower_mu_multiplicity
- shower_mu_bundle_log_energy
- shower_mu_singleness
- shower_mu_bundle_energy_fraction
- shower_mu_leading_energy_fraction
